name: Deploy .NET Core application to windows webapp PawNClawDevelopmentAPI with API Management Service PawNClawDevelopmentAPI
on:
  push:
    branches:
    - dev
env:
  AZURE_WEBAPP_NAME: PawNClawDevelopmentAPI
  AZURE_WEBAPP_PACKAGE_PATH: ./publish
  AZURE_APIM_RESOURCE_PATH: /
  AZURE_APIM_RESOURCEGROUP: PawNClaw
  AZURE_APIM_SERVICENAME: PawNClawDevelopmentAPI
  AZURE_APIM_API_ID: PawNClawDevelopmentAPI
  AZURE_APIM_APPSERVICEURL: https://pawnclawdevelopmentapi.azurewebsites.net
  API_IMPORT_SPECIFICATION_PATH: ./publish/swagger.json
jobs:
  deploy:
    runs-on: windows-latest
    needs: build
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.PawNClawDevelopmentAPI_spn }}
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.PawNClawDevelopmentAPI_83ce }}
    - name: Import API into Azure API Management
      run: az apim api import --path "${{ env.AZURE_APIM_RESOURCE_PATH }}" --resource-group "${{ env.AZURE_APIM_RESOURCEGROUP }}" --service-name "${{ env.AZURE_APIM_SERVICENAME }}" --api-id "${{ env.AZURE_APIM_API_ID }}" --service-url "${{ env.AZURE_APIM_APPSERVICEURL }}" --specification-path "${{ env.API_IMPORT_SPECIFICATION_PATH }}" --specification-format OpenApi --subscription-required false
    - name: logout
      run: >
        az logout
